init:
# Carriage returns are bad
  - git config --global core.autocrlf input

install:
  - choco install cyg-get
  - set PATH=%PATH%;C:\cygwin
  - "cyg-get make >> cyg-get.log"
  - "cyg-get mingw64-i686-gcc-core >> cyg-get.log"
  - "cyg-get mingw64-x86_64-gcc-core >> cyg-get.log"

build_script:
  - C:\cygwin\bin\sh -lc "uname -a;
      i686-w64-mingw32-gcc --version;
      x86_64-w64-mingw32-gcc --version;
      cd /cygdrive/c/projects/ecos;
      sed -i 's/ifdef _WIN64/if 0/' external/SuiteSparse_config/SuiteSparse_config.h;
      mkdir -p usr32/bin usr64/bin;
      CC='i686-w64-mingw32-gcc -g -Wl,--stack,8388608' make test shared;
      ./ecostester.exe;
      mv libecos.d* usr32/bin/libecos.dll;
      make purge && rm -f ecostester.exe;
      CC='x86_64-w64-mingw32-gcc -g -Wl,--stack,8388608' make test shared;
      ./ecostester.exe;
      mv libecos.d* usr64/bin/libecos.dll;
      7z a ecos-$APPVEYOR_REPO_COMMIT.7z usr32 usr64 COPYING"

artifacts:
  - path: 'ecos-*.7z'
